logging: 
  level:
    org:
      springframework:
        boot: ERROR
springdoc:
  swagger-ui:
    path: /api/docs
    disable-swagger-default-url: 'true'
server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: 123456
    key-store-type: pkcs12
    key-alias: springboot
    key-password: 123456
  port: 8080