spring.profiles.active: local
---
santander:
  region: boae
  suffix:
  app-name: mportal
  logging:
    format: GLUONLOG
    gluon-log:
      company: ems
      componentName: mp0001
      componentId: CHANGEIT_CMPT_ID
      componentType: microservice
      appId: CHANGEIT_APP_ID
    entity: ESP
    paas-app-version: "1.2.1"
    kafka:
      server: ${env.logging-server}
  core:
    exceptions:
      error-format: GLUON
  security:
    connectors:
      pkm-connector:
        pkm-endpoint:
          - ${env.pkm-endpoint}
    caffeine:
      # disable null values in cache for performance reasons
      allow-null-values: false

spring:
  data:
    mongodb:
      uri: ${env.mongodb.uri}
      database: ${env.mongodb.database}
  application:
    name: ems-mportal-mp0001
  session:
    store-type: none
  cache:
    type: CAFFEINE #Activated cache caffeine by default (If you want to change the cache to JBoss DataGrid, check the documentacion in confluence)
    caffeine:
      spec: expireAfterWrite=10m #Specifies that each entry should be automatically removed from the cache once that duration has elapsed after the entryâ€™s creation
  lifecycle.timeout-per-shutdown-phase: 2m

logging.level:
  com.santander.ems.mportal.emsmportalmp0001: INFO
  root: WARN

management:
  endpoint.health:
    show-details: ALWAYS

health:
  config:
    enabled: false

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

server:
  max-http-request-header-size: 128KB
  forward-headers-strategy: framework
  shutdown: graceful
  port: 8080

app:
  cos:
    jweurl: ${env.commerce-portal.cos.jwe-url}
    keyalias: ${env.commerce-portal.cos.keyalias}
    santander-client-id: ${env.commerce-portal.cos.santander-client-id}
  sas:
    auth-url: ${env.commerce-portal.sas.auth-url}
    credential-type-jwt: ${env.commerce-portal.sas.credential-type-jwt}
    credential-type-token-corp: ${env.commerce-portal.sas.credential-type-token-corp}
    uid: ${env.commerce-portal.sas.uid}
    password: ${env.commerce-portal.sas.password}
    realm: ${env.commerce-portal.sas.realm}
  nuek:
    commerces: ${env.commerce-portal-portal.commerces-url}