server:
  port: 8080

logging:
  level:
    root: ERROR
    com.santander: INFO

spring:
  profiles:
    active: test
  application:
    name: gpp-srv-merchant-portal-service
    version: 1.0.0-SNAPSHOT

getnet:
  client:
    nuek-auth:
      url: https://srvnuarintra.santander.pru.bsch
    nuek:
      url: https://repgtnprep.minsaitpaymentsprocessing.com